version: "3"
services:
  client:
    image: "josua96/multi-client"
    # hostname is like the named ip for the container that will be running this image
    # docker will redirect to this container all those request whose their hostname is client
    mem_limit: 128m
    hostname: client
  server:
    image: "josua96/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "josua96/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    depends_on: # make nginx start once the client and the api were started
      - server
      - client
    image: "josua96/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"